### ISSUE TITLE
Add an explanation of using the find and replace tool to the descriptive analysis I lab code

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/intro.r.public#12]
# Overview

The students need to be able to use the find and replace tool to efficiently complete the descriptive analysis I module quiz. Previously, they were given some really explicit instructions for doing so in the descriptive analysis I lab. There is still an example in the lab they can use for practice, but at some point, the explicit instructions were removed and there was a lot of confusion on the quiz. I think adding explicit instructions back to the lab will help with the confusion on the quiz. 

## Update 2023-05-14

It turns out that there are some instructions for using the find and replace tool in the [descriptive analysis I lab](https://github.com/brad-cannell/intro.r.public/blob/main/modules/03%20Descriptive%20Analysis%20I/lab_descriptive_analysis_I.Rmd). They are immediately following Task 9. However, I don't think they are as extensive as they were at some point in the past. The really comprehensive instructions are gone. What to do now?

- I could just rewrite them. However, I don't think the descriptive analysis I lab actually needs more instructions. 
- I could just add some hints to the Google Doc and Canvas for the descriptive analysis I module quiz. I will probably do this. 
- I might also want to consider adding a [section to R4Epi](https://github.com/orgs/brad-cannell/projects/3/views/6?pane=issue&itemId=29071514) explaining how to use the find and replace tool.

# Tasks

- [x] See if you can find the old instructions
- [x] Add instructions for using the find and replace tool to the descriptive analysis I google doc and quiz text in Canvas.
- [ ] Add a [section to R4Epi](https://github.com/orgs/brad-cannell/projects/3/views/6?pane=issue&itemId=29071514) explaining how to use the find and replace tool.

**Comment by mbcann01** [comment]
For now, I added the following additional instructions to the Descriptive Analysis I module quiz [Google Doc](https://docs.google.com/document/d/1N5oxaezZjG5_6hgXHjk_aSluyWPCOH16nbeZgLzQLNk/edit) and [Canvas instructions](https://uth.instructure.com/courses/79593/quizzes/100246).

- Create a new data frame by copying the data values above and pasting them into a new R code chunk.
- To reduce the amount of manual typing required to turn this data into an R data frame, I recommend that you do the following.
  - Create the data frame with the tribble() function (with an “r”) instead of the tibble() or data.frame() functions. In case you missed it, here is a [link to the section in R4Epi](https://www.r4epi.com/lets-get-programming.html#the-tribble-function) that introduces the tribble() function.
  - Use RStudio’s Find and Replace Tool to add in the appropriate spacing, commas, and quotation marks. In case you missed it, there are some notes on using the find and replace tool in the [descriptive analysis I lab code file](https://uthtmc-my.sharepoint.com/:u:/g/personal/michael_b_cannell_uth_tmc_edu/Ecdt_Uw6inhNleEXWWY2G24Bu4cnijmnTUut9R-3Cie-xw?e=FDW4LO) that was provided to you.
