### ISSUE TITLE
Repeated Operations I Module Quiz

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/intro.r.public#19]
# Overview

We need to create a first draft of this assignment. Please add your files to the appropriate folder in the [intro.r.private GitHub repository](https://github.com/brad-cannell/intro.r.private).

## Development Notes

- We should just read-in Rds files that are ready for the repeated operations examples. Nothing extraneous. 
- This module quiz should cover the material in the Repeated Operations I lab pretty closely.

### Writing Functions

- [ ] When to write functions
- [ ] Parts of a function
- [ ] How to write fucntions
- [ ] Giving functions default values
- [ ] Return values
- [ ] Lexical scoping
- [ ] Tidy evaluation
- [ ] Convert 7 and 9 to missing (may have to update the data) using a user defined function and across().
- [ ] Write a function to calculate continuous stats using the temps data (https://app.clickup.com/t/td2th7)
- [ ] Write a function to calculate categorical stats using class survey data (https://app.clickup.com/t/td2thb)

### Column-wise operations

- [ ] Rename multiple columns with rename_with and a character vector (may have to give the study data generic names to start with).
- [ ] The across() function arguments 
  - [ ] Assign new variable names with across() inside mutate() using the .names argument.
- [ ] Across() with mutate(). 
  - [ ] Convert multiple column types at once with across().
  - [ ] Convert character vectors to factors using across()
- [ ] Across() with summarise()
  - [ ] Calculate the number of missing for each variable using across() with summarize. 
  - [ ] Pivot summary stats table.
- [ ] Use across() with filter() to do complete case analysis.
- [ ]  In the restructuring data lab, I wanted to graph mean repeat time by initial incident complaint. This was going to be really hard without repeated operations. Show them how to do it with repeated operations. (https://app.clickup.com/t/td2th9)

# Set up tasks

- [ ] Prep the class survey data
- [ ] Prep the temps 2012 data

# Left off

2023-07-23: I didn't get this finished in time to add it to Canvas this semester. Try again next semester.
- I was working on this quiz in tandem with making updates to the lab (#19).
- I reviewed task 1-3 in the lab.
- When you start again, finish reviewing task 4 in the lab and then make a similar task in the module quiz. You started to do this, but didn't finish.

# Tasks after development

- [ ] Update [module quiz Rmd](https://uthtmc.sharepoint.com/:f:/r/sites/SPHCannellIntrotoR/Shared%20Documents/intro.r.private/modules/11%20Repeated%20Operations%20I?csf=1&web=1&e=ajxov1) file (you should be doing this _during_ development).
(https://docs.google.com/document/d/1favXZxalFtpj5lLCo3bg0G7AVRKdDbG6gOfF_CiJqCg/edit)
- [ ] Update the quiz in Canvas

**Comment by mbcann01** [comment]
2024-07-25: Once again, I didn't get this done this summer, and I need to push it to next year.
