### ISSUE TITLE
Initial repository set up

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/intro.r.public#2]
# Overview

I want to create two repositories for Introduction to R Programming and Data Management that are similar to the two I set up for Epidemiology III. 
* https://github.com/brad-cannell/epi_3_public
* https://github.com/brad-cannell/epi_3_private

## Repository names

I would have liked to use underscores in the repository name (i.e., intro_r_public) rather than dots (i.e., intro.r.public); however, I think there is a fairly reasonable chance that I will want to use this repository as a package that students can download datasets and code from. R package names are not allowed to have underscores. The only other option was camel case (i.e., introRPublic) and I think that is even worse than dots. 

## Tasks

- [x] Create intro.r.public
- [x] Create intro.r.private
- [x] Add lab code to intro.r.public - similar to Epi III
- [x] Add module quiz code to intro.r.private - similar to Epi III
- [x] Add instructions for TA's to the repository's wiki
